openapi: 3.1.0
info:
  title: Ingredients API
  description: Ingredients API
  version: 1.0.0
servers:
  - url: 'http://localhost:8080'
paths:
  /ingredients:
    get:
      summary: Récupérer tous les ingrédients
      tags:
        - Ingredients
      responses:
        '200':
          description: Liste de tous les ingrédients
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Ingredient'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: string

  /ingredients/{id}:
    get:
      summary: Récupérer un ingrédient par id
      tags:
        - Ingredients
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Ingrédient ayant l'id correspondant
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ingredient'
        '404':
          description: Ingrédient non trouvé
          content:
            application/json:
              schema:
                type: string
                example: "Ingredient.id=1 is not found"

  /ingredients/{id}/stock:
    get:
      summary: Retourner la valeur de stock d'un ingrédient à une date précise
      tags:
        - Ingredient
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            example: 1
        - name: at
          in: query
          required: false
          schema:
            type: string
            example: "2024-01-06T12:00:00Z"
        - name: unit
          in: query
          required: false
          schema:
            type: string
            example: "KG"
      responses:
        '200':
          description: Succès
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Stock'
        '404':
          description: Ingrédient non trouvé
          content:
            application/json:
              schema:
                type: string
                example: "Ingredient.id=1 is not found"
        '400':
          description: Paramètres non fournis
          content:
            application/json:
              schema:
                type: string
                example: " “Either mandatory query parameter `at` or `unit` is not provided"










components:
  schemas:
    Ingredient:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: "tomate"
        price:
          type: number
          format: double
        category:
          type: string
          enum:
            - VEGETABLE
            - ANIMAL
            - MARINE
            - DAIRY
            - OTHER
          example: "VEGETABLE"
    Stock:
      type: object
      properties:
        quantity:
          type: number
          format: double
        unit:
          type: string
          enum:
            - PCS
            - KG
            - L
          example: "KG"



